#!/bin/bash

# Script to unpack various archive formats

if [ -z "$1" ]; then
    echo "Usage: unpack <file>"
    exit 1
fi

file=$1

# Determine the file extension
case $file in
    *.tar.bz2)  tar xjf "$file" ;;
    *.tar.gz)   tar xzf "$file" ;;
    *.tar.xz)   tar xf "$file" ;;
    *.bz2)      bunzip2 "$file" ;;
    *.rar)      unrar x "$file" ;;
    *.gz)       gunzip "$file" ;;
    *.tar)      tar xf "$file" ;;
    *.tbz2)     tar xjf "$file" ;;
    *.tgz)      tar xzf "$file" ;;
    *.zip)      unzip "$file" ;;
    *.Z)        uncompress "$file" ;;
    *.7z)       7z x "$file" ;;
    *.deb)
        dir="${file%.deb}"
        mkdir -p "$dir"
        cd "$dir" || exit
        ar x "../$file"
        tar -xf data.tar.* ;;
    *)
        echo "unpack: '$file' cannot be unpacked with this script."
        exit 1
        ;;
esac

echo "Unpacked: $file"

